# Generated by Django 5.0.1 on 2026-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_task_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='درباره'),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تخصص'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='backlogs', to='core.tag'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='core.tag'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sprints', to='core.tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.tag'),
        ),
    ]
