# Generated by Django 5.0.1 on 2026-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_user_bio_user_expertise_backlog_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='user_story',
            field=models.TextField(blank=True, null=True, verbose_name='یوزر استوری'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='user_story',
            field=models.TextField(blank=True, null=True, verbose_name='یوزر استوری'),
        ),
    ]
